Repository ssg-240304-java2/OOP-javaMart, pull requests merged in 2024-04, with the labels that each got.

#1 리드미 file update
  JunRyeol.md
  README.md
Labels: documentation

#2 프로젝트 개요
  JAVA_Mart/.gitignore
  JAVA_Mart/build.gradle
  JAVA_Mart/gradle/wrapper/gradle-wrapper.jar
  JAVA_Mart/gradle/wrapper/gradle-wrapper.properties
  JAVA_Mart/gradlew
  JAVA_Mart/gradlew.bat
  JAVA_Mart/settings.gradle
  README.md
Labels: documentation

#3 Update README.md file
  README.md
Labels: update

#5 생성자 posDTO 완성
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/Application.java
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/PosDTO.java
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/PosMenu.java
Labels: 📘documentation

#4 Update issue templates
  .github/ISSUE_TEMPLATE/✅--feature.md
  .github/ISSUE_TEMPLATE/❌-error.md
Labels: 🔧update

#7 메뉴 생성 및 출력문 작성
  .idea/OOP-javaMart.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/Application.java
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/PosDTO.java
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/PosMenu.java
Labels: ✨ Feature

#8 menu added with storage method completed
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/Application.java
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/PosMenu.java
Labels: 🔧update, ✨ Feature

#13 Feature : 품목별 매출 계산 메소드 추가
  .idea/workspace.xml
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/controller/PosMenu.java
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/dto/PosDTO.java
Labels: ✨ Feature

#18 메소드 생성 및 댑스 수정
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/controller/PosMenu.java
Labels: 🔧update

#20 전체 재고 및 매출 출력
  .idea/workspace.xml
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/controller/PosMenu.java
  JAVA_Mart/src/main/java/com/JavaMart/out/production/JavaMart/com/JavaMart/OOP_javaMart/controller/PosMenu.class
  JAVA_Mart/src/main/java/com/JavaMart/out/production/JavaMart/com/JavaMart/OOP_javaMart/dto/PosDTO.class
  JAVA_Mart/src/main/java/com/JavaMart/out/production/JavaMart/com/JavaMart/OOP_javaMart/run/Application.class
Labels: ✨ Feature

#26 update: menu() 수정 및 주석추가
  .idea/compiler.xml
  .idea/misc.xml
  .idea/workspace.xml
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/controller/PosMenu.java
  JAVA_Mart/src/main/java/com/JavaMart/OOP_javaMart/dto/PosDTO.java
  README.md
Labels: ❌ Error, 🔧update
